### ISSUE TITLE
Cache mismatch

### ISSUE THREAD

**Issue by Partiolainen** [anton-martyniuk/Modern#10]
Hi

When option `AddOrUpdateInCacheWhenEntityIsUpdated` is enabled, Update method stores dto to cache without includes. When option is disabled we can take only outdated dto from cache with Get methods
So we in trap) 

I think it is necessary to delete from the cache when updating and the option `AddOrUpdateInCacheWhenEntityIsUpdated` is disabled

Something like
```
if (!_options.Value.AddOrUpdateInCacheWhenEntityIsUpdated)
{
   await Cache.DeleteAsync(id).ConfigureAwait(false);
   return MapToDto(entityDbo);
}
```

Thank you for awesome framework!

**Comment by anton-martyniuk** [comment]
@Partiolainen thanks, I am glad to hear that you liked the Modern framework.
Indeed it's a bug in my code with an outdated value being left in the Cache.
I plan to delete the item from Cache in the `ModernCachedService` and `ModernInMemoryService` as you suggested.

I will release a fix today.

Meanwhile in the EF Core mapping you can mark a child entity with `AutoInclude()` when specifying a navigation, so when retrieved from the database it will be automatically included in every query:
https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#model-configuration-for-auto-including-navigations

**Comment by anton-martyniuk** [comment]
@Partiolainen I've published Modern.Services.DataStore.Cached 2.0.1, Modern.Services.DataStore.InMemory 2.0.1 to Nuget with a fixes. Please try and confirm if the issue is resolved. Happy coding

**Comment by Partiolainen** [comment]
Resolved, ty!
